[package]
name = "mukernel"
version = "0.1.0"
authors = ["Isitha Subasinghe"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic="abort"

[profile.release]
panic="abort"


[dependencies]
